---
- name: install packages
  yum: name={{ item }} state=latest
  with_items:
    - gcc-c++
    - make
- name: install nodejs
  yum: name=https://rpm.nodesource.com/pub_6.x/el/7/x86_64/nodejs-6.11.2-1nodesource.el7.centos.x86_64.rpm state=present
- name: install packages
  yum: name={{ item }} state=latest
  with_items:
    - nodejs
